[package]
name = "trinity-gui"
description = "Iced GUI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "trinity-gui"
path = "src/main.rs"

[dependencies]
trinity-core = { path = "../trinity-core" }
trinity-app = { path = "../trinity-app" }
iced = { version = "0.14", features = ["tokio", "svg"] }
xkbcommon = "0.9"
rust-i18n = "4"
serde = { version = "1", features = ["derive"] }
toml = "0.9"
dirs = "6"

[lints]
workspace = true
